openapi: 3.0.0
info:
  title: ePrint API
  description: API para la gestión de impresión y versiones de ePrint
  version: 1.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/organizacion-117/ePrint/1.0.0
  - url: http://localhost:5000
    description: Servidor local

paths:
  /:
    get:
      tags:
       - Peticiones
      summary: Página de inicio
      description: Devuelve la página de inicio con información de la plataforma
      responses:
        "200":
          description: Página cargada correctamente

  /management/about:
    get:
      tags:
       - Peticiones
      summary: Obtiene información del sistema
      description: Devuelve información sobre la configuración y estado del sistema
      responses:
        "200":
          description: Información obtenida con éxito
        "500":
          description: Error al obtener la información

  /management/print:
    get:
      tags:
       - Peticiones
      summary: Lista impresoras disponibles
      description: Devuelve una lista con las impresoras y si soportan impresión a doble cara
      responses:
        "200":
          description: Lista de impresoras obtenida con éxito

  /management/docs:
    get:
      tags:
       - Peticiones
      summary: Obtiene información de la API
      description: Devuelve la documentación y estado de la API
      responses:
        "200":
          description: Información de la API obtenida con éxito
        "500":
          description: Error al obtener la API

  /management/versions:
    get:
      tags:
       - Peticiones
      summary: Obtiene las versiones de la aplicación
      description: Lista de versiones con sus notas de lanzamiento
      responses:
        "200":
          description: Lista de versiones obtenida con éxito
        "500":
          description: Error al obtener las versiones

  /printers:
    get:
      tags:
       - Impresoras
      summary: Obtiene las impresoras disponibles en el equipo
      description: Lista de impresoras del equipo con información detallada sobre duplex, copias y caras soportadas
      responses:
        "200":
          description: Lista de impresoras obtenida con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Printer"

  /printers/{printer_id}:
    post:
      tags:
       - Impresoras
      summary: Enviar documento a la impresora
      description: Envía un archivo para ser impreso en una impresora específica
      parameters:
        - name: printer_id
          in: path
          required: true
          description: ID de la impresora de destino
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Archivo a imprimir
                copies:
                  type: integer
                  description: Número de copias a imprimir
      responses:
        "200":
          description: Documento enviado a imprimir con éxito
        "400":
          description: No se ha subido ningún archivo o formato no soportado
        "500":
          description: Error en la impresión

  /management/settings:
    get:
      tags:
       - Configuración
      summary: Obtiene los ajustes de la impresora
      description: Devuelve los ajustes de la impresora desde la configuración
      responses:
        "200":
          description: Ajustes obtenidos con éxito
        "500":
          description: Error al obtener los ajustes
    post:
      tags:
       - Configuración
      summary: Guarda los ajustes de la impresora
      description: Permite guardar la configuración de la impresora seleccionada, incluyendo el número de copias y la opción de impresión a doble cara.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PrinterSettings"
      responses:
        "200":
          description: Ajustes guardados correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de confirmación
        "400":
          description: Error en los parámetros de configuración

  /management/licenses:
    get:
      tags:
       - Licencias
      summary: Obtiene información sobre licencias
      description: Muestra información sobre librerías y derechos de autor utilizados en el sistema.
      responses:
        "200":
          description: Licencias obtenidas con éxito

components:
  schemas:
    Printer:
      type: object
      properties:
        name:
          type: string
          description: Nombre de la impresora
        duplex:
          type: boolean
          description: Indica si la impresora soporta impresión a doble cara
        copies:
          type: integer
          description: Número de copias predeterminado
        sides:
          type: integer
          description: Número de caras soportadas (1 para una cara, 2 para doble cara)
        dpi:
          type: integer
          description: Resolución DPI de la impresora
        max_dpi:
          type: integer
          description: Resolución máxima DPI de la impresora

    PrinterSettings:
      type: object
      properties:
        printer:
          type: string
          description: Nombre de la impresora
        copies:
          type: integer
          description: Número de copias a imprimir
        sides:
          type: integer
          description: Número de caras (1 para una cara, 2 para doble cara)
        dpi:
          type: integer
          description: Resolución DPI de la impresora
        max_dpi:
          type: integer
          description: Resolución máxima DPI de la impresora
